#!/usr/bin/env zsh


# Constants 

PORTFOLIOPATH="../assets/img/portfolio/"
HTMLPATH="../assets/img/portfolio/"
OUTPUTHTML="../index_gen.html"
HEADHTML="../head.html"
TAILHTML="../tail.html"

# Check we are rnning this script from the correct subdirectory
if [[ `pwd | awk -F "/" '{print $NF}'` != "scripts" ]] ; then
  echo "Please run this shell script from the scripts directory"
  exit 1
fi  
 
# save previos html files
cp $OUTPUTHTML $OUTPUTHTML.prev
# copy our heder to the new index file
cat $HEADHTML > $OUTPUTHTML 
# add comment header to html
echo "             <!-- Autogenerated portfolio-items --> \n" >> $OUTPUTHTML
# loop through image files
for i in `find $PORTFOLIOPATH -name "*.webp" | awk -F "/" '{print $NF}'`;
do
  DESCRIPTION="test description"
  NAME=`echo $i | sed 's/\.webp$//' | awk -F "-" '{print $2, $3}'`
  # build the profolio-item html

  FILTER=`echo $i | awk -F "-" '{print $1}'`
  # class
  echo "\n" \
       "          <div class=\"col-lg-4 col-md-6 portfolio-item isotope-item filter-$FILTER\"> \n" \
       "            <img src="\"$HTMLPATH$i\"" class="img-fluid" alt=\"\" > \n" \
       "            <div class="portfolio-info"> \n" \
       "              <p>$DESCRIPTION<p> \n" \
       "              <h4>$NAME</h4> \n" \
       "              <p>$DESCRIPTION</p> \n" \
       "              <a href=\"$HTMLPATH`echo $i | awk -F "." '{print $1}'`.png\" title=\"$NAME\" data-gallery=\"portfolio-gallery-$FILTER\" class=\"glightbox preview-link\"><i class=\"bi bi-zoom-in\"></i></a> \n" \
       "            </div> \n" \
       "          </div><!-- End Portfolio Item --> \n" >> $OUTPUTHTML

done;

  echo "           <!-- End of Autogenerated portfolio-items  html --> \n" >> $OUTPUTHTML

# copy our footer to the new index file
cat $TAILHTML >> $OUTPUTHTML 

